

INSERT INTO "TIM_VIDEO_SYSTEMS" ("TVS_VIDEO_SYSTEM_ID", "TVS_VIDEO_SYSTEM_NAME") VALUES ( 10,'MARK')
INSERT INTO "TIM_VIDEO_SYSTEMS" ("TVS_VIDEO_SYSTEM_ID", "TVS_VIDEO_SYSTEM_NAME") VALUES ( 11,'VEGARD')
INSERT INTO "TIM_VIDEO_SYSTEMS" ("TVS_VIDEO_SYSTEM_ID", "TVS_VIDEO_SYSTEM_NAME") VALUES ( 12,'MANOS')
INSERT INTO "TIM_VIDEO_SYSTEMS" ("TVS_VIDEO_SYSTEM_ID", "TVS_VIDEO_SYSTEM_NAME") VALUES ( 13,'MATIAS')
INSERT INTO "TIM_VIDEO_SYSTEMS" ("TVS_VIDEO_SYSTEM_ID", "TVS_VIDEO_SYSTEM_NAME") VALUES ( 14,'ALEXANDRA') 

INSERT INTO "TIM_VIDEOS" ("TIV_ID", "TIV_VIDEO_SYSTEM_ID","TIV_KEYSTAKENDATA_TAGID","TIV_REGISTRATIONDATA_TAGID","TIV_ACTIVATIONDATA_TAGID","TIV_HOST","TIV_CAMERA","TIV_LOGIN","TIV_PASSWORD","TIV_DESCRIPTION") VALUES  ( 12,12,12,12,12,'TEST6',10,'TEST6','TEST6','TEST6')
INSERT INTO "TIM_VIDEOS" ("TIV_ID", "TIV_VIDEO_SYSTEM_ID","TIV_KEYSTAKENDATA_TAGID","TIV_REGISTRATIONDATA_TAGID","TIV_ACTIVATIONDATA_TAGID","TIV_HOST","TIV_CAMERA","TIV_LOGIN","TIV_PASSWORD","TIV_DESCRIPTION") VALUES  ( 11,11,11,11,11,'TEST1',10,'TEST1','TEST1','TEST1')
INSERT INTO "TIM_VIDEOS" ("TIV_ID", "TIV_VIDEO_SYSTEM_ID","TIV_KEYSTAKENDATA_TAGID","TIV_REGISTRATIONDATA_TAGID","TIV_ACTIVATIONDATA_TAGID","TIV_HOST","TIV_CAMERA","TIV_LOGIN","TIV_PASSWORD","TIV_DESCRIPTION") VALUES  ( 10,10,10,10,10,'TEST2',10,'TEST2','TEST2','TEST2')
INSERT INTO "TIM_VIDEOS" ("TIV_ID", "TIV_VIDEO_SYSTEM_ID","TIV_KEYSTAKENDATA_TAGID","TIV_REGISTRATIONDATA_TAGID","TIV_ACTIVATIONDATA_TAGID","TIV_HOST","TIV_CAMERA","TIV_LOGIN","TIV_PASSWORD","TIV_DESCRIPTION") VALUES  ( 12,12,12,12,12,'TEST3',10,'TEST3','TEST3','TEST3')
INSERT INTO "TIM_VIDEOS" ("TIV_ID", "TIV_VIDEO_SYSTEM_ID","TIV_KEYSTAKENDATA_TAGID","TIV_REGISTRATIONDATA_TAGID","TIV_ACTIVATIONDATA_TAGID","TIV_HOST","TIV_CAMERA","TIV_LOGIN","TIV_PASSWORD","TIV_DESCRIPTION") VALUES  ( 13,13,13,13,13,'TEST4',10,'TEST4','TEST4','TEST4')