CREATE TABLE dmn_equipment_v (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY (START WITH 1) NOT NULL PRIMARY KEY,
    equipment_name VARCHAR(4000),
    equipment_rule_tag_id INTEGER NOT NULL,
    CONSTRAINT TUC_MAP_DEF_1 UNIQUE (equipment_name,equipment_rule_tag_id)
);


INSERT INTO dmn_equipment_v (equipment_name,equipment_rule_tag_id) VALUES ('TESTDEVICE1',100);
INSERT INTO dmn_equipment_v (equipment_name,equipment_rule_tag_id) VALUES ('TESTDEVICE2',222);


CREATE TABLE dmn_metric_v (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY (START WITH 1) NOT NULL PRIMARY KEY,
    device VARCHAR(4000) NOT NULL,
    property VARCHAR(4000) NOT NULL,
    field VARCHAR(4000) NOT NULL,
    metric_rule_tag_id INTEGER NOT NULL,
    CONSTRAINT TUC_METRIC_DEF_1 UNIQUE (device,property,field)
);


INSERT INTO dmn_metric_v (device, property, field, metric_rule_tag_id) VALUES ('DIAMON.CLIC.CS-CCR-DEV2','Acquisition', 'ntp.avg', 188866);
INSERT INTO dmn_metric_v (device, property, field, metric_rule_tag_id) VALUES ('DIAMON.CLIC.CS-CCR-DEV2','Acquisition', 'sys.kern.activeproc', 188864);


