
CREATE TABLE dmn_process_v (
    process_id INTEGER GENERATED BY DEFAULT AS IDENTITY (START WITH 1) NOT NULL PRIMARY KEY,    
    process_name VARCHAR(4000) NOT NULL,
    equipment_type_name VARCHAR(100) NOT NULL,    
    CONSTRAINT TUC_PR_DEF_1 UNIQUE (process_name)    
);

INSERT INTO dmn_process_v (process_name,equipment_type_name) VALUES('P_CLIC_01','CLIC');
INSERT INTO dmn_process_v (process_name,equipment_type_name) VALUES('P_CLIC_02','CLIC');

CREATE TABLE dmn_equipment_v (
    equipment_id INTEGER NOT NULL PRIMARY KEY,    
    equipment_name VARCHAR(4000) NOT NULL,
    process_id INTEGER NOT NULL,
    equipment_rule_tag_id INTEGER NOT NULL,
    CONSTRAINT TUC_EQ_DEF_1 UNIQUE (equipment_name,equipment_rule_tag_id)    
);


INSERT INTO dmn_equipment_v (equipment_id,equipment_name,process_id,equipment_rule_tag_id) VALUES (1,'TESTDEVICE1',1,100);
INSERT INTO dmn_equipment_v (equipment_id,equipment_name,process_id,equipment_rule_tag_id) VALUES (2,'TESTDEVICE2',1,222);
INSERT INTO dmn_equipment_v (equipment_id,equipment_name,process_id,equipment_rule_tag_id) VALUES (3,'TESTDEVICE3',2,223);


CREATE TABLE dmn_metric_v (    
    metric_data_tag_id INTEGER NOT NULL PRIMARY KEY,
    equipment_id INTEGER NOT NULL,
    metric_name VARCHAR(4000) NOT NULL,   
    display_name VARCHAR(4000) NOT NULL,
    metric_rule_tag_id INTEGER,
    data_type VARCHAR(100) NOT NULL,
    test_id INTEGER NOT NULL,    
    description VARCHAR(4000),
    CONSTRAINT TUC_MET_DEF_1 UNIQUE (metric_name)
);


INSERT INTO dmn_metric_v (metric_data_tag_id,equipment_id,metric_name,display_name,metric_rule_tag_id,data_type,test_id,description) 
VALUES (10001,1,'CLIC:CS-CCR-DEV2:METRIC1','METRIC1',188866,'Integer',1,'description metric1');

INSERT INTO dmn_metric_v (metric_data_tag_id,equipment_id,metric_name,display_name,metric_rule_tag_id,data_type,test_id,description) 
VALUES (10002,1,'CLIC:CS-CCR-DEV2:METRIC2','METRIC2',188864,'Integer',1,'description metric2');

INSERT INTO dmn_metric_v (metric_data_tag_id,equipment_id,metric_name,display_name,metric_rule_tag_id,data_type,test_id,description) 
VALUES (10003,3,'CLIC:CS-CCR-DEV2:METRIC3','METRIC3',null,'Integer',1,'description metric3');
