
/**********************************************************************************************/
/************************************** TABLES ************************************************/
/**********************************************************************************************/

DROP TABLE IF EXISTS c2mon_config;
CREATE TABLE c2mon_config (
    configid INTEGER GENERATED BY DEFAULT AS IDENTITY (START WITH 1000) NOT NULL PRIMARY KEY,    
    configname VARCHAR(60) NOT NULL,
    configdesc VARCHAR(120) NOT NULL,
    author VARCHAR(60) NOT NULL,        
    configstate VARCHAR(1) ,
    createdate timestamp,
    applydate  timestamp,
    status VARCHAR(1),    
    applied_by VARCHAR(20),
);
