ALTER SEQUENCE CONFIG_ID_SEQUENCE RESTART WITH 1;
ALTER SEQUENCE PROCESS_ID_SEQUENCE RESTART WITH 10000;
ALTER SEQUENCE EQUIPMENT_ID_SEQUENCE RESTART WITH 100000;
ALTER SEQUENCE TAG_ID_SEQUENCE RESTART WITH 300000;
ALTER SEQUENCE ALARM_ID_SEQUENCE RESTART WITH 300000;