/******************************************************************************
 * This file is part of the Technical Infrastructure Monitoring (TIM) project.
 * See http://ts-project-tim.web.cern.ch
 * 
 * Copyright (C) 2004 - 2011 CERN This program is free software; you can
 * redistribute it and/or modify it under the terms of the GNU General Public
 * License as published by the Free Software Foundation; either version 2 of the
 * License, or (at your option) any later version. This program is distributed
 * in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even
 * the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
 * See the GNU General Public License for more details. You should have received
 * a copy of the GNU General Public License along with this program; if not,
 * write to the Free Software Foundation, Inc., 59 Temple Place - Suite 330,
 * Boston, MA 02111-1307, USA.
 * 
 * Author: TIM team, tim.support@cern.ch
 *****************************************************************************/
package cern.c2mon.client.history.tag;

import java.sql.Timestamp;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.Collection;

import cern.c2mon.client.common.history.HistoryTagValueUpdate;
import cern.c2mon.shared.client.alarm.AlarmValue;
import cern.c2mon.shared.client.tag.TagMode;
import cern.c2mon.shared.client.tag.TagValueUpdate;
import cern.tim.shared.common.datatag.DataTagQuality;

/**
 * Implementation of the {@link TagValueUpdate}
 * 
 * @author vdeila
 * 
 */
public class HistoryTagValueUpdateImpl implements HistoryTagValueUpdate {

  /** the tag identifier */
  private final Long id;

  /** the DataTagQuality object for this data tag. */
  private final DataTagQuality dataTagQuality;

  /** the tag value */
  private final Object value;

  /**
   * This timestamp indicates when the tag value event was generated by the
   * source.
   */
  private final Timestamp sourceTimestamp;

  /**
   * This timestamp indicates when the tag value passed the server. Please
   * notice that the source timestamp and server timestamp might be the same in
   * case that the value change event was generated by the server itself.
   */
  private final Timestamp serverTimestamp;

  /** the tag value description */
  private final String description;

  /**
   * The collection of registered alarms or an empty list, if no alarm is
   * defined
   */
  private final Collection<AlarmValue> alarms;

  /** the current mode of the tag. */
  private final TagMode mode;

  /**
   * <code>true</code>, if the tag value is currently simulated and not
   * corresponding to a live event.
   */
  private final boolean isSimulated;

  /** The data type of the value */
  private String dataType;

  /**
   * 
   * @param id
   *          the tag identifier
   * @param dataTagQuality
   *          the DataTagQuality object for this data tag.
   * @param value
   *          the tag value
   * @param sourceTimestamp
   *          This timestamp indicates when the tag value event was generated by
   *          the source.
   * @param serverTimestamp
   *          This timestamp indicates when the tag value passed the server.
   *          Please notice that the source timestamp and server timestamp might
   *          be the same in case that the value change event was generated by
   *          the server itself.
   * @param description
   *          the tag value description
   * @param alarms
   *          The collection of registered alarms or an empty list, if no alarm
   *          is defined
   * @param mode
   *          the current mode of the tag.
   */
  public HistoryTagValueUpdateImpl(final Long id, final DataTagQuality dataTagQuality, final Object value, final Timestamp sourceTimestamp,
      final Timestamp serverTimestamp, final String description, final AlarmValue[] alarms, final TagMode mode) {
    this.id = id;
    this.dataTagQuality = dataTagQuality;
    this.value = value;
    this.sourceTimestamp = sourceTimestamp;
    this.serverTimestamp = serverTimestamp;
    this.description = description;
    this.mode = mode;
    this.isSimulated = true;
    this.alarms = new ArrayList<AlarmValue>();
    if (alarms != null) {
      this.alarms.addAll(Arrays.asList(alarms));
    }
  }

  /**
   * 
   * @param id
   *          the tag identifier
   * @param dataTagQuality
   *          the DataTagQuality object for this data tag.
   * @param value
   *          the tag value
   * @param sourceTimestamp
   *          This timestamp indicates when the tag value event was generated by
   *          the source.
   * @param serverTimestamp
   *          This timestamp indicates when the tag value passed the server.
   *          Please notice that the source timestamp and server timestamp might
   *          be the same in case that the value change event was generated by
   *          the server itself.
   * @param description
   *          the tag value description
   * @param mode
   *          the current mode of the tag.
   */
  public HistoryTagValueUpdateImpl(final Long id, final DataTagQuality dataTagQuality, final Object value, final Timestamp sourceTimestamp,
      final Timestamp serverTimestamp, final String description, final TagMode mode) {
    this(id, dataTagQuality, value, sourceTimestamp, serverTimestamp, description, null, mode);
  }

  @Override
  public Collection<AlarmValue> getAlarms() {
    return this.alarms;
  }

  @Override
  public DataTagQuality getDataTagQuality() {
    return this.dataTagQuality;
  }

  @Override
  public String getDescription() {
    return this.description;
  }

  @Override
  public Long getId() {
    return this.id;
  }

  @Override
  public TagMode getMode() {
    return this.mode;
  }

  @Override
  public Timestamp getServerTimestamp() {
    return this.serverTimestamp;
  }

  @Override
  public Timestamp getSourceTimestamp() {
    return this.sourceTimestamp;
  }

  @Override
  public Object getValue() {
    return this.value;
  }

  @Override
  public boolean isSimulated() {
    return this.isSimulated;
  }

  /**
   * @return the dataType
   */
  @Override
  public String getDataType() {
    return dataType;
  }

  /**
   * @param dataType the dataType to set
   */
  public void setDataType(final String dataType) {
    this.dataType = dataType;
  }

  /**
   * @return the string representation of the object
   */
  @Override
  public String toString() {
    return String.format("Id: %d, ServerTime: %s", getId(), getServerTimestamp().toString());
  }

  /**
   * 
   * @return the time of when this update should execute
   */
  @Override
  public Timestamp getExecutionTimestamp() {
    return getServerTimestamp();
  }
  
  

}
