##
# Simple Workflow with SNAPSHOT build from Master, including Sonar quality checks.
# Artifacts are deployed to a non-public repository
##

image: gitlab-registry.cern.ch/industrial-controls/sw-infra/jenkins/mvn-plus-jdk

stages:
- build
- deploy
- sonar

# Get the settings file from c2mon project
before_script:
  - curl http://timweb.cern.ch/m2/c2mon-internal-settings.xml -o settings.xml

# Fully build and publish master branch
build_and_publish:
  stage: deploy
  script: 
    - mvn -B deploy -Djavax.net.ssl.trustStore=${CACERTS} --settings settings.xml
  only:
    - master
    - develop
    
# Just run tests on feature branches
build:
  stage: build
  script:
    - mvn -B test --settings settings.xml
  except:
    - master
    - develop

sonar_preview:
  type: sonar
  script:
    - mvn -B compile sonar:sonar -Dmaven.test.skip=true -Djavax.net.ssl.trustStore=${CACERTS} -Dsonar.analysis.mode=preview -Dsonar.gitlab.commit_sha=$CI_BUILD_REF -Dsonar.gitlab.ref_name=$CI_BUILD_REF_NAME -Dsonar.gitlab.project_id=$CI_PROJECT_ID -Dsonar.gitlab.max_major_issues_gate=0 --settings settings.xml
  except:
    - master
    - tags

quality_assurance:
  stage: sonar
  script:
    - mvn package sonar:sonar -Dmaven.test.skip=true -Djavax.net.ssl.trustStore=${CACERTS} -Dsonar.dependencyCheck.reportPath=target/dependency-check-report.xml --settings settings.xml
  only:
    - master
  except:
    - tags
