{
 "title": "Hostmetrics",
 "description": "Metrics for the host machine of the Hostmetrics-DAQ process",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Running threads",
   "type": "graph",
   "description": "Number of threads running in the host",
   "gridPos": { "h": 10, "w": 17, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "SELECT TAGTIME  AS \"time\",   \nTAGNAME  AS metric,   \ncast(TAGVALUE as UNSIGNED) as value\nFROM SHORTTERMLOG \nWHERE TAGID = '100012'\nORDER BY TAGTIME;"
    }
   ]
  },
  {
   "title": "System Load",
   "type": "gauge",
   "description": "The system load average over the last minute",
   "gridPos": { "h": 9, "w": 6, "x": 18, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT TAGTIME  AS \"time\",   \nTAGNAME AS metric,   \ncast(TAGVALUE as UNSIGNED) as value\nFROM SHORTTERMLOG \nWHERE TAGID = '100008'\nORDER BY TAGTIME;"
    }
   ]
  },
  {
   "title": "Available Memory",
   "type": "graph",
   "description": "The memory available in the host, in Gigabytes",
   "gridPos": { "h": 14, "w": 12, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "decgbytes" }
   ],
   "targets": [
    {
     "rawSql": "SELECT TAGTIME  AS \"time\",   \nTAGNAME  AS metric,   \ncast(TAGVALUE as UNSIGNED) / 1000000000 as value\nFROM SHORTTERMLOG \nWHERE TAGID = '100006'\nORDER BY TAGTIME;"
    }
   ]
  },
  {
   "title": "Open File descriptors",
   "type": "graph",
   "description": "The count of file descriptors currently open on the host",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 10 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "SELECT TAGTIME  AS \"time\",   \nTAGNAME  AS metric,   \ncast(TAGVALUE as UNSIGNED) as value\nFROM SHORTTERMLOG \nWHERE TAGID = '100013'\nORDER BY TAGTIME;"
    }
   ]
  }
 ]
}