

-- process P_HOST01 and its control tags
INSERT INTO DATATAG (TAGID, TAGNAME, TAGMODE, TAGDATATYPE, TAGCONTROLTAG, TAGLOGGED, TAGQUALITYCODE, TAGQUALITYDESC)
VALUES (2001, 'P_HOST01:STATUS', 0, 'String', 1, 1, 1, 'UNINITIALISED');
INSERT INTO DATATAG (TAGID, TAGNAME, TAGMODE, TAGDATATYPE, TAGCONTROLTAG, TAGLOGGED, TAGQUALITYCODE, TAGQUALITYDESC)
VALUES (2002, 'P_HOST01:ALIVE', 0, 'Long', 1, 0, 1, 'UNINITIALISED');
INSERT INTO PROCESS (PROCID, PROCNAME, PROCDESC, PROCSTATE_TAGID, PROCALIVE_TAGID, PROCALIVEINTERVAL, PROCMAXMSGSIZE, PROCMAXMSGDELAY, PROCSTATE)
VALUES (200, 'P_HOST01', '', 2001, 2002, 30000, 100, 300, 'DOWN');

-- equipment E_HOST01 and its control tags
INSERT INTO DATATAG (TAGID, TAGNAME, TAGMODE, TAGDATATYPE, TAGCONTROLTAG, TAGLOGGED, TAGQUALITYCODE, TAGQUALITYDESC)
VALUES (3001, 'E_HOST01:STATUS', 0, 'String', 1, 1, 1, 'UNINITIALISED');
INSERT INTO DATATAG (TAGID, TAGNAME, TAGMODE, TAGDATATYPE, TAGCONTROLTAG, TAGLOGGED, TAGQUALITYCODE, TAGQUALITYDESC)
VALUES (3002, 'E_HOST01:COMM_FAULT', 0,'Boolean', 1, 1, 1, 'UNINITIALISED');
INSERT INTO DATATAG (TAGID, TAGNAME, TAGMODE, TAGDATATYPE, TAGCONTROLTAG, TAGLOGGED, TAGQUALITYCODE, TAGQUALITYDESC)
VALUES (3003, 'E_HOST01:ALIVE', 0, 'Long', 1, 0, 1, 'UNINITIALISED');
INSERT INTO EQUIPMENT (EQID, EQNAME, EQDESC, EQHANDLERCLASS, EQSTATE_TAGID, EQALIVE_TAGID, EQALIVEINTERVAL, EQCOMMFAULT_TAGID, EQ_PROCID, EQADDRESS)
VALUES (300, 'E_HOST01', '', 'cern.c2mon.daq.hostmetrics.HostMetricsMessageHandler', 3001, 3003, 60000, 3002, 200, '');

-- data tags for E_HOST01
INSERT INTO DATATAG (TAGID, TAGNAME, TAGDESC, TAGMODE, TAGDATATYPE, TAGCONTROLTAG, TAGLOGGED, TAGQUALITYCODE, TAGQUALITYDESC, TAG_EQID, TAGADDRESS, TAGUNIT, TAGMETADATA)
VALUES (210000, 'mem.avail', 'Available memory', 0, 'Long', 0, 1, 1, 'UNINITIALISED', 300, '<DataTagAddress></DataTagAddress>', 'bytes', '{"responsible":"Joe Bloggs"}');
INSERT INTO DATATAG (TAGID, TAGNAME, TAGDESC, TAGMODE, TAGDATATYPE, TAGCONTROLTAG, TAGLOGGED, TAGQUALITYCODE, TAGQUALITYDESC, TAG_EQID, TAGADDRESS, TAGUNIT, TAGMETADATA)
VALUES (210001, 'mem.swap.used', 'Amount of swap space used', 0, 'Long', 0, 1, 1, 'UNINITIALISED', 300, '<DataTagAddress></DataTagAddress>', 'bytes', '{"responsible":"Joe Bloggs"}');
INSERT INTO DATATAG (TAGID, TAGNAME, TAGDESC, TAGMODE, TAGDATATYPE, TAGCONTROLTAG, TAGLOGGED, TAGQUALITYCODE, TAGQUALITYDESC, TAG_EQID, TAGADDRESS, TAGMETADATA)
VALUES (210002, 'cpu.loadavg', 'CPU load average for the last minute', 0, 'Double', 0, 1, 1, 'UNINITIALISED', 300, '<DataTagAddress></DataTagAddress>', '{"responsible":"John Doe"}');
INSERT INTO DATATAG (TAGID, TAGNAME, TAGDESC, TAGMODE, TAGDATATYPE, TAGCONTROLTAG, TAGLOGGED, TAGQUALITYCODE, TAGQUALITYDESC, TAG_EQID, TAGADDRESS, TAGUNIT, TAGMETADATA)
VALUES (210003, 'cpu.temp', 'CPU temperature', 0, 'Double', 0, 1, 1, 'UNINITIALISED', 300, '<DataTagAddress></DataTagAddress>', 'Celsius', '{"responsible":"John Doe"}');
INSERT INTO DATATAG (TAGID, TAGNAME, TAGDESC, TAGMODE, TAGDATATYPE, TAGCONTROLTAG, TAGLOGGED, TAGQUALITYCODE, TAGQUALITYDESC, TAG_EQID, TAGADDRESS, TAGUNIT, TAGMETADATA)
VALUES (210004, 'cpu.voltage', 'CPU voltage', 0, 'Double', 0, 1, 1, 'UNINITIALISED', 300, '<DataTagAddress></DataTagAddress>', 'Volts', '{"responsible":"John Doe"}');
INSERT INTO DATATAG (TAGID, TAGNAME, TAGDESC, TAGMODE, TAGDATATYPE, TAGCONTROLTAG, TAGLOGGED, TAGQUALITYCODE, TAGQUALITYDESC, TAG_EQID, TAGADDRESS, TAGMETADATA)
VALUES (210005, 'os.numprocs', 'Number of running processes', 0, 'Integer', 0, 1, 1, 'UNINITIALISED', 300, '<DataTagAddress></DataTagAddress>', '{"responsible":"Sue West"}');
INSERT INTO DATATAG (TAGID, TAGNAME, TAGDESC, TAGMODE, TAGDATATYPE, TAGCONTROLTAG, TAGLOGGED, TAGQUALITYCODE, TAGQUALITYDESC, TAG_EQID, TAGADDRESS, TAGMETADATA)
VALUES (210006, 'os.numthreads', 'Number of running threads', 0, 'Integer', 0, 1, 1, 'UNINITIALISED', 300, '<DataTagAddress></DataTagAddress>', '{"responsible":"Sue West"}');
INSERT INTO DATATAG (TAGID, TAGNAME, TAGDESC, TAGMODE, TAGDATATYPE, TAGCONTROLTAG, TAGLOGGED, TAGQUALITYCODE, TAGQUALITYDESC, TAG_EQID, TAGADDRESS, TAGMETADATA)
VALUES (210007, 'os.fds', 'Number of open file descriptors', 0, 'Long', 0, 1, 1, 'UNINITIALISED', 300, '<DataTagAddress></DataTagAddress>', '{"responsible":"Sue West"}');
