package ch.cern.tim.driver.jintegraInterface;

import com.linar.jintegra.*;

/**
 * COM Class 'OPCGroups'. Generated 10/5/2006 11:24:10 AM
 * from 'G:\Users\t\timoper\Public\opcdaauto.dll'<P>
 * Generated using com2java Version 2.6 Copyright (c) Intrinsyc Software International, Inc.
 * See  <A HREF="http://j-integra.intrinsyc.com/">http://j-integra.intrinsyc.com/</A><P>
 * Description '<B>OPC Automation Groups Collection</B>'
 *
 * Generator Options:
 *   AwtForOcxs = False
 *   PromptForTypeLibraries = False
 *   RetryOnReject = False
 *   IDispatchOnly = False
 *   GenBeanInfo = False
 *   LowerCaseMemberNames = True
 *   TreatInStarAsIn = False
 *   ArraysAsObjects = False
 *   OmitRestrictedMethods = False
 *   ClashPrefix = zz_
 *   ImplementConflictingInterfaces = False
 *   DontRenameSameMethods = False
 *   RenameConflictingInterfaceMethods = False
 *   ReuseMethods = False
 *
 * Command Line Only Options:
 *   MakeClsidsPublic = False
 *   DontOverwrite = False
 */
public class OPCGroups implements com.linar.jintegra.RemoteObjRef, ch.cern.tim.driver.jintegraInterface.IOPCGroups {

  private static final String CLSID = "28e68f9e-8d75-11d1-8dc3-3c302a000000";

  protected String getJintegraVersion() { return "2.6"; }

  // Interface delegates
  private ch.cern.tim.driver.jintegraInterface.IOPCGroupsProxy d_IOPCGroupsProxy = null;

  /** Access this COM class's ch.cern.tim.driver.jintegraInterface.IOPCGroups interface */
  public ch.cern.tim.driver.jintegraInterface.IOPCGroups getAsIOPCGroups() { return d_IOPCGroupsProxy; }

  /** Compare this object with another */
  public boolean equals(Object o) { 
	if(java.beans.Beans.isDesignTime()) return super.equals(o);
	else return getJintegraDispatch() == null ? false : getJintegraDispatch().equals(o);
  }


  /** the hashcode for this object */
  public int hashCode() { return getJintegraDispatch() == null ? 0 : getJintegraDispatch().hashCode(); }

   /**
   * getActiveObject. Get a reference to a running instance of this class on the current machine using native code.
   *                  <B>Uses native code (See GetActiveObject() in MS doc) and thus can only be used on MS Windows</B>
   *
   * @return    A reference to the running object.
   * @exception java.io.IOException If there are communications problems.
   * @exception com.linar.jintegra.AutomationException If there was an error attaching to the instance.
   */
  public static OPCGroups getActiveObject() throws com.linar.jintegra.AutomationException, java.io.IOException {
    return new OPCGroups(com.linar.jintegra.Dispatch.getActiveObject(CLSID));
  }

  /**
   * bindUsingMoniker. Bind to a running instance of this class using the supplied ObjRef moniker
   *
   * @return    A reference to the running object.
   * @param     moniker The ObjRef Moniker (Created using Windows CreateObjrefMoniker() and IMoniker->GetDisplayName).
   * @exception java.io.IOException If there are communications problems.
   * @exception com.linar.jintegra.AutomationException If there was an error attaching to the instance.
   */
  public static OPCGroups bindUsingMoniker(String moniker) throws com.linar.jintegra.AutomationException, java.io.IOException {
    return new OPCGroups(com.linar.jintegra.Dispatch.bindUsingMoniker(moniker));
  }

  /** J-Integra for COM internal method */
  public com.linar.jintegra.Dispatch getJintegraDispatch() {  return d_IOPCGroupsProxy; }

  /**
   * addDIOPCGroupsEventListener.  Listen to events generated by this class.
   *
   * @param    theListener An object that implements the ch.cern.tim.driver.jintegraInterface.DIOPCGroupsEvent interface.
   * @exception java.io.IOException If there are communications problems.
   */
  public void addDIOPCGroupsEventListener(ch.cern.tim.driver.jintegraInterface.DIOPCGroupsEvent theListener) throws java.io.IOException {
    d_IOPCGroupsProxy.addListener("28e68f9d-8d75-11d1-8dc3-3c302a000000", theListener, this);
  }

  /**
   * removeDIOPCGroupsEventListener.  Stop listening to events generated by this class.
   *
   * @param    theListener An object that implements the ch.cern.tim.driver.jintegraInterface.DIOPCGroupsEvent interface.
   * @exception java.io.IOException If there are communications problems.
   */
  public void removeDIOPCGroupsEventListener(ch.cern.tim.driver.jintegraInterface.DIOPCGroupsEvent theListener) throws java.io.IOException {
    d_IOPCGroupsProxy.removeListener("28e68f9d-8d75-11d1-8dc3-3c302a000000", theListener);
  }

  /**
   * Constructs a OPCGroups on the local host.
   * @exception java.io.IOException if there are problems communicating via DCOM 
   * @exception java.net.UnknownHostException if the host can not be found 
   */
  public OPCGroups() throws java.io.IOException, java.net.UnknownHostException {
    this("localhost");
  }

  /**
   * Construct a OPCGroups on specified host.
   * @param     host  the host on which the object should be created
   * @exception java.io.IOException if there are problems communicating via DCOM 
   * @exception java.net.UnknownHostException if the host can not be found 
   */
  public OPCGroups(String host) throws java.io.IOException, java.net.UnknownHostException {
    d_IOPCGroupsProxy = new ch.cern.tim.driver.jintegraInterface.IOPCGroupsProxy(CLSID, host, null);
  }

  /**
   * Construct a OPCGroups using a reference to such an object returned from a COM server
   * @param     obj an object returned from a COM server
   * @exception java.io.IOException if there are problems communicating via DCOM 
   */
  public OPCGroups(Object obj) throws java.io.IOException {
    d_IOPCGroupsProxy = new ch.cern.tim.driver.jintegraInterface.IOPCGroupsProxy(obj);
  }

  /**
   * Release a OPCGroups.
   */
  public void release() {
    com.linar.jintegra.Cleaner.release(d_IOPCGroupsProxy);
  }

  /**
   * getPropertyByName. Get the value of a property dynamically at run-time, based on its name
   *
   * @return    The value of the property.
   * @param     name The name of the property to get.
   * @exception java.lang.NoSuchFieldException If the property does not exit.
   * @exception java.io.IOException If there are communications problems.
   * @exception com.linar.jintegra.AutomationException If the remote server throws an exception.
   */
  public Object getPropertyByName(String name) throws NoSuchFieldException, java.io.IOException, com.linar.jintegra.AutomationException {
    try {
      return d_IOPCGroupsProxy.getPropertyByName(name);
    } catch(com.linar.jintegra.AutomationException automationException) {
      automationException.fillInStackTrace();
      throw automationException;
    } catch(NoSuchFieldException noSuchFieldException) {
      noSuchFieldException.fillInStackTrace();
      throw noSuchFieldException;
    }
  }

  /**
   * getPropertyByName. Get the value of a property dynamically at run-time, based on its name and a parameter
   *
   * @return    The value of the property.
   * @param     name The name of the property to get.
   * @param     rhs A parameter used when getting the proxy.
   * @exception java.lang.NoSuchFieldException If the property does not exit.
   * @exception java.io.IOException If there are communications problems.
   * @exception com.linar.jintegra.AutomationException If the remote server throws an exception.
   */
  public Object getPropertyByName(String name, Object rhs) throws NoSuchFieldException, java.io.IOException, com.linar.jintegra.AutomationException {
    try {
      return d_IOPCGroupsProxy.getPropertyByName(name, rhs);
    } catch(com.linar.jintegra.AutomationException automationException) {
      automationException.fillInStackTrace();
      throw automationException;
    } catch(NoSuchFieldException noSuchFieldException) {
      noSuchFieldException.fillInStackTrace();
      throw noSuchFieldException;
    }
  }

  /**
   * invokeMethodByName. Invoke a method dynamically at run-time
   *
   * @return    The value returned by the method (null if none).
   * @param     name The name of the method to be invoked.
   * @param     parameters One element for each parameter. Use primitive type wrappers.
   *            to pass primitive types (eg Integer to pass an int).
   * @exception java.lang.NoSuchMethodException If the method does not exit.
   * @exception java.io.IOException If there are communications problems.
   * @exception com.linar.jintegra.AutomationException If the remote server throws an exception.
   */
  public Object invokeMethodByName(String name, Object[] parameters) throws NoSuchMethodException, java.io.IOException, com.linar.jintegra.AutomationException {
    return d_IOPCGroupsProxy.invokeMethodByName(name, parameters);
  }

  /**
   * invokeMethodByName. Invoke a method dynamically at run-time
   *
   * @return    The value returned by the method (null if none).
   * @param     name The name of the method to be invoked.
   * @exception java.lang.NoSuchMethodException If the method does not exit.
   * @exception java.io.IOException If there are communications problems.
   * @exception com.linar.jintegra.AutomationException If the remote server throws an exception.
   */
  public Object invokeMethodByName(String name) throws NoSuchMethodException, java.io.IOException, com.linar.jintegra.AutomationException {
    return d_IOPCGroupsProxy.invokeMethodByName(name, new Object[]{});
  }

  /**
   * getParent. Returns the parent OPCServer
   *
   * @return    An reference to a ch.cern.tim.driver.jintegraInterface.IOPCAutoServer
   * @exception java.io.IOException If there are communications problems.
   * @exception com.linar.jintegra.AutomationException If the remote server throws an exception.
   */
  public ch.cern.tim.driver.jintegraInterface.IOPCAutoServer getParent  () throws java.io.IOException, com.linar.jintegra.AutomationException {
    try {
      return d_IOPCGroupsProxy.getParent();
    } catch(com.linar.jintegra.AutomationException automationException) {
      automationException.fillInStackTrace();
      throw automationException;
    }
  }

  /**
   * isDefaultGroupIsActive. Gets the default active state for the collection.
   *
   * @return    The defaultGroupIsActive
   * @exception java.io.IOException If there are communications problems.
   * @exception com.linar.jintegra.AutomationException If the remote server throws an exception.
   */
  public boolean isDefaultGroupIsActive  () throws java.io.IOException, com.linar.jintegra.AutomationException {
    try {
      return d_IOPCGroupsProxy.isDefaultGroupIsActive();
    } catch(com.linar.jintegra.AutomationException automationException) {
      automationException.fillInStackTrace();
      throw automationException;
    }
  }

  /**
   * setDefaultGroupIsActive. Gets the default active state for the collection.
   *
   * @param     defaultGroupIsActive The defaultGroupIsActive (in)
   * @exception java.io.IOException If there are communications problems.
   * @exception com.linar.jintegra.AutomationException If the remote server throws an exception.
   */
  public void setDefaultGroupIsActive  (
              boolean defaultGroupIsActive) throws java.io.IOException, com.linar.jintegra.AutomationException {
    try {
      d_IOPCGroupsProxy.setDefaultGroupIsActive(defaultGroupIsActive);
    } catch(com.linar.jintegra.AutomationException automationException) {
      automationException.fillInStackTrace();
      throw automationException;
    }
  }

  /**
   * getDefaultGroupUpdateRate. Gets the default update rate for the collection.
   *
   * @return    The defaultGroupUpdateRate
   * @exception java.io.IOException If there are communications problems.
   * @exception com.linar.jintegra.AutomationException If the remote server throws an exception.
   */
  public int getDefaultGroupUpdateRate  () throws java.io.IOException, com.linar.jintegra.AutomationException {
    try {
      return d_IOPCGroupsProxy.getDefaultGroupUpdateRate();
    } catch(com.linar.jintegra.AutomationException automationException) {
      automationException.fillInStackTrace();
      throw automationException;
    }
  }

  /**
   * setDefaultGroupUpdateRate. Gets the default update rate for the collection.
   *
   * @param     defaultGroupUpdateRate The defaultGroupUpdateRate (in)
   * @exception java.io.IOException If there are communications problems.
   * @exception com.linar.jintegra.AutomationException If the remote server throws an exception.
   */
  public void setDefaultGroupUpdateRate  (
              int defaultGroupUpdateRate) throws java.io.IOException, com.linar.jintegra.AutomationException {
    try {
      d_IOPCGroupsProxy.setDefaultGroupUpdateRate(defaultGroupUpdateRate);
    } catch(com.linar.jintegra.AutomationException automationException) {
      automationException.fillInStackTrace();
      throw automationException;
    }
  }

  /**
   * getDefaultGroupDeadband. Gets the default deadband for the collection.
   *
   * @return    The defaultGroupDeadband
   * @exception java.io.IOException If there are communications problems.
   * @exception com.linar.jintegra.AutomationException If the remote server throws an exception.
   */
  public float getDefaultGroupDeadband  () throws java.io.IOException, com.linar.jintegra.AutomationException {
    try {
      return d_IOPCGroupsProxy.getDefaultGroupDeadband();
    } catch(com.linar.jintegra.AutomationException automationException) {
      automationException.fillInStackTrace();
      throw automationException;
    }
  }

  /**
   * setDefaultGroupDeadband. Gets the default deadband for the collection.
   *
   * @param     defaultGroupDeadband The defaultGroupDeadband (in)
   * @exception java.io.IOException If there are communications problems.
   * @exception com.linar.jintegra.AutomationException If the remote server throws an exception.
   */
  public void setDefaultGroupDeadband  (
              float defaultGroupDeadband) throws java.io.IOException, com.linar.jintegra.AutomationException {
    try {
      d_IOPCGroupsProxy.setDefaultGroupDeadband(defaultGroupDeadband);
    } catch(com.linar.jintegra.AutomationException automationException) {
      automationException.fillInStackTrace();
      throw automationException;
    }
  }

  /**
   * getDefaultGroupLocaleID. Gets the default locale setting for the collection.
   *
   * @return    The defaultGroupLocaleID
   * @exception java.io.IOException If there are communications problems.
   * @exception com.linar.jintegra.AutomationException If the remote server throws an exception.
   */
  public int getDefaultGroupLocaleID  () throws java.io.IOException, com.linar.jintegra.AutomationException {
    try {
      return d_IOPCGroupsProxy.getDefaultGroupLocaleID();
    } catch(com.linar.jintegra.AutomationException automationException) {
      automationException.fillInStackTrace();
      throw automationException;
    }
  }

  /**
   * setDefaultGroupLocaleID. Gets the default locale setting for the collection.
   *
   * @param     defaultGroupLocaleID The defaultGroupLocaleID (in)
   * @exception java.io.IOException If there are communications problems.
   * @exception com.linar.jintegra.AutomationException If the remote server throws an exception.
   */
  public void setDefaultGroupLocaleID  (
              int defaultGroupLocaleID) throws java.io.IOException, com.linar.jintegra.AutomationException {
    try {
      d_IOPCGroupsProxy.setDefaultGroupLocaleID(defaultGroupLocaleID);
    } catch(com.linar.jintegra.AutomationException automationException) {
      automationException.fillInStackTrace();
      throw automationException;
    }
  }

  /**
   * getDefaultGroupTimeBias. Gets the default time bias for the collection.
   *
   * @return    The defaultGroupTimeBias
   * @exception java.io.IOException If there are communications problems.
   * @exception com.linar.jintegra.AutomationException If the remote server throws an exception.
   */
  public int getDefaultGroupTimeBias  () throws java.io.IOException, com.linar.jintegra.AutomationException {
    try {
      return d_IOPCGroupsProxy.getDefaultGroupTimeBias();
    } catch(com.linar.jintegra.AutomationException automationException) {
      automationException.fillInStackTrace();
      throw automationException;
    }
  }

  /**
   * setDefaultGroupTimeBias. Gets the default time bias for the collection.
   *
   * @param     defaultGroupTimeBias The defaultGroupTimeBias (in)
   * @exception java.io.IOException If there are communications problems.
   * @exception com.linar.jintegra.AutomationException If the remote server throws an exception.
   */
  public void setDefaultGroupTimeBias  (
              int defaultGroupTimeBias) throws java.io.IOException, com.linar.jintegra.AutomationException {
    try {
      d_IOPCGroupsProxy.setDefaultGroupTimeBias(defaultGroupTimeBias);
    } catch(com.linar.jintegra.AutomationException automationException) {
      automationException.fillInStackTrace();
      throw automationException;
    }
  }

  /**
   * getCount. Gets number of groups in the collection.
   *
   * @return    The count
   * @exception java.io.IOException If there are communications problems.
   * @exception com.linar.jintegra.AutomationException If the remote server throws an exception.
   */
  public int getCount  () throws java.io.IOException, com.linar.jintegra.AutomationException {
    try {
      return d_IOPCGroupsProxy.getCount();
    } catch(com.linar.jintegra.AutomationException automationException) {
      automationException.fillInStackTrace();
      throw automationException;
    }
  }

  /**
   * get_NewEnum. 
   *
   * @return    An enumeration.
   * @exception java.io.IOException If there are communications problems.
   * @exception com.linar.jintegra.AutomationException If the remote server throws an exception.
   */
  public java.util.Enumeration get_NewEnum  () throws java.io.IOException, com.linar.jintegra.AutomationException {
    try {
      return d_IOPCGroupsProxy.get_NewEnum();
    } catch(com.linar.jintegra.AutomationException automationException) {
      automationException.fillInStackTrace();
      throw automationException;
    }
  }

  /**
   * item. Returns an OPCGroup by index (starts at 1) or name
   *
   * @param     itemSpecifier A Variant (in)
   * @return    An reference to a ch.cern.tim.driver.jintegraInterface.OPCGroup
   * @exception java.io.IOException If there are communications problems.
   * @exception com.linar.jintegra.AutomationException If the remote server throws an exception.
   */
  public ch.cern.tim.driver.jintegraInterface.OPCGroup item  (
              Object itemSpecifier) throws java.io.IOException, com.linar.jintegra.AutomationException {
    try {
      return d_IOPCGroupsProxy.item(itemSpecifier);
    } catch(com.linar.jintegra.AutomationException automationException) {
      automationException.fillInStackTrace();
      throw automationException;
    }
  }

  /**
   * add. Adds an OPCGroup to the collection
   *
   * @param     name A Variant (in, optional, pass null if not required)
   * @return    An reference to a ch.cern.tim.driver.jintegraInterface.OPCGroup
   * @exception java.io.IOException If there are communications problems.
   * @exception com.linar.jintegra.AutomationException If the remote server throws an exception.
   */
  public ch.cern.tim.driver.jintegraInterface.OPCGroup add  (
              Object name) throws java.io.IOException, com.linar.jintegra.AutomationException {
    try {
      return d_IOPCGroupsProxy.add(name);
    } catch(com.linar.jintegra.AutomationException automationException) {
      automationException.fillInStackTrace();
      throw automationException;
    }
  }

  /**
   * getOPCGroup. Returns an OPCGroup specified by server handle or name
   *
   * @param     itemSpecifier A Variant (in)
   * @return    An reference to a ch.cern.tim.driver.jintegraInterface.OPCGroup
   * @exception java.io.IOException If there are communications problems.
   * @exception com.linar.jintegra.AutomationException If the remote server throws an exception.
   */
  public ch.cern.tim.driver.jintegraInterface.OPCGroup getOPCGroup  (
              Object itemSpecifier) throws java.io.IOException, com.linar.jintegra.AutomationException {
    try {
      return d_IOPCGroupsProxy.getOPCGroup(itemSpecifier);
    } catch(com.linar.jintegra.AutomationException automationException) {
      automationException.fillInStackTrace();
      throw automationException;
    }
  }

  /**
   * removeAll. Remove all groups and their items
   *
   * @exception java.io.IOException If there are communications problems.
   * @exception com.linar.jintegra.AutomationException If the remote server throws an exception.
   */
  public void removeAll  () throws java.io.IOException, com.linar.jintegra.AutomationException {
    try {
      d_IOPCGroupsProxy.removeAll();
    } catch(com.linar.jintegra.AutomationException automationException) {
      automationException.fillInStackTrace();
      throw automationException;
    }
  }

  /**
   * remove. Removes an OPCGroup specified by server handle or name
   *
   * @param     itemSpecifier A Variant (in)
   * @exception java.io.IOException If there are communications problems.
   * @exception com.linar.jintegra.AutomationException If the remote server throws an exception.
   */
  public void remove  (
              Object itemSpecifier) throws java.io.IOException, com.linar.jintegra.AutomationException {
    try {
      d_IOPCGroupsProxy.remove(itemSpecifier);
    } catch(com.linar.jintegra.AutomationException automationException) {
      automationException.fillInStackTrace();
      throw automationException;
    }
  }

  /**
   * connectPublicGroup. Adds an existing public OPCGroup to the collection
   *
   * @param     name The name (in)
   * @return    An reference to a ch.cern.tim.driver.jintegraInterface.OPCGroup
   * @exception java.io.IOException If there are communications problems.
   * @exception com.linar.jintegra.AutomationException If the remote server throws an exception.
   */
  public ch.cern.tim.driver.jintegraInterface.OPCGroup connectPublicGroup  (
              String name) throws java.io.IOException, com.linar.jintegra.AutomationException {
    try {
      return d_IOPCGroupsProxy.connectPublicGroup(name);
    } catch(com.linar.jintegra.AutomationException automationException) {
      automationException.fillInStackTrace();
      throw automationException;
    }
  }

  /**
   * removePublicGroup. Removes a public OPCGroup specified by server handle or name
   *
   * @param     itemSpecifier A Variant (in)
   * @exception java.io.IOException If there are communications problems.
   * @exception com.linar.jintegra.AutomationException If the remote server throws an exception.
   */
  public void removePublicGroup  (
              Object itemSpecifier) throws java.io.IOException, com.linar.jintegra.AutomationException {
    try {
      d_IOPCGroupsProxy.removePublicGroup(itemSpecifier);
    } catch(com.linar.jintegra.AutomationException automationException) {
      automationException.fillInStackTrace();
      throw automationException;
    }
  }

}
