source "https://rubygems.org"

# Set to 3.7.3 for github-pages compat
gem "jekyll", "~> 3.9.0"

# If you have any plugins, put them here!
group :jekyll_plugins do
  gem "jekyll-feed", "~> 0.11.0"
  gem 'github-pages', '~> 207'
end
