source "https://rubygems.org"

# Set to 3.7.3 for github-pages compat
gem "jekyll", "~> 3.8.5"

# If you have any plugins, put them here!
group :jekyll_plugins do
  gem "jekyll-feed", "~> 0.13.0"
  gem 'github-pages', '~> 203'
end
